Add RGB-D Camera
Field-Robotics-Japan/UnitySensorsArchive pull request #19
Opened 2022-09-07 06:16 UTC by Autumn60

## デプスカメラのスクリプト追加

### 追加されたアセット類

* Camera.cs：カメラから取得したColorBuffer及びDepthBufferをDepth.csに送信し、計算結果の点群データを受信
* Depth.cs(ComputeShader)：Depth計算用のコンピュートシェーダー。PointCloud2MsgへのSerializerの機能を兼ねている。if文を内部で使用しているため、高速化の余地あり。

2022-10-16 07:58 UTC, RyodoTanaka requested changes
動作確認しましたが，下記設定でも添付のようにデータが歪んでしまいました．
設定等を教えてください．
よろしくおねがいします．
![Screenshot from 2022-10-16 16-43-49](https://user-images.githubusercontent.com/8377208/196024808-79c242ad-bce3-48fe-8a35-539a1d68ed88.png)

![Screenshot from 2022-10-16 16-33-44](https://user-images.githubusercontent.com/8377208/196024812-8092b729-27f1-4906-84a4-d4608c6a571d.png)

2022-10-16 08:00 UTC, RyodoTanaka commented
@Autumn60 
なお，最終的な作業ブランチは下記で検証しています．
https://github.com/arav-jp/UnitySensorsROSAssets/tree/feature/add-rgbd

2022-10-17 01:04 UTC, Autumn60 commented
![image](https://user-images.githubusercontent.com/37181352/196068088-ef95a50d-33c8-477b-9553-5e7781767b71.png)

分かりにくい機能を削除し、動作確認しました。
(と言っても、変更を行う前の時点で動作確認が行えたので、原因がいまいち分かっていないです。)

・Unityのカメラコンポーネントの設定はTarget Displayを除いてデフォルト値です(FOVの設定項目をCameraスクリプト側に追加)
・Cameraスクリプトの"Set FOV"ボタンは、Sceneビュー内で画角を確認する時を除いて押す必要は無いです(実行時に同様の処理が走ります)

2022-10-19 02:08 UTC, RyodoTanaka commented
@Autumn60 
設定値を見直しましたが，値が送信されません．
また，今回のPRスクリプトを追加すると，他のトピックも全て停止してしまします．
https://github.com/arav-jp/UnitySensorsROSAssets/tree/fix/rgbd-bug
こちらの Sceneファイルに追加の Azure Kinect モジュールで実行中です．

上記Sceneをご確認いただき，そちらの内容にて修正が必要な場合，UnitySensorsROSAssets にもPRをください．
よろしくおねがいします．

2023-01-24 08:33 UTC, Autumn60 commented
https://docs.unity3d.com/ja/2018.4/Manual/class-ComputeShader.html

ComputeShaderのサポート範囲が原因である可能性があります。

Debug.Log(SystemInfo.supportsComputeShaders);
をCamera.csのUpdate関数内に入れて、ComputeShaderが使用できるかどうか確認していただきたいです。


~~~C#
private void Update()
{
    Debug.Log(SystemInfo.supportsComputeShaders);
}
~~~

2023-01-24 08:40 UTC, RyodoTanaka commented
@Autumn60 
True でした...！
詰まりサポートされている...

2023-01-30 02:29 UTC, Autumn60 commented
↑コミット内容

・Gizmosでの点群表示の際にカメラの回転が考慮されていない問題を修正
・1画素分の座標ズレを修正
・Resolution計算修正
・ComputeShader内のuintで良い計算をintからuintに修正

2023-02-02 04:30 UTC, Autumn60 commented
↑コミット内容

・Gizmos表示の座標変換を再修正

2023-02-06 02:18 UTC, RyodoTanaka commented
本件，Windowsなら動作するところまで確認済．
Linux で動作するまではマージしない予定です．；

2023-03-22 09:51 UTC, Autumn60 commented
恐らくDepthBufferの仕様が原因であるという結論に至り、以下の修正を行いました。

* OpenGLの仕様に合わせてComputeShaderを書き直し、Linux環境のみ動作を確認しました。
* クラス名CameraがUnityEngine.Cameraと被っていたためDCameraに修正しました

また、PointCloud2について正常な動作が確認されるまで、ImageをPubする機能はオミットします。

2023-03-24 05:12 UTC, Autumn60 commented
上記コミットで、Windows環境（DirectX環境）でも動作を確認しました。
また、Gizmosによる負荷を考慮して、Sceneビューに表示する点群の最大数を制限できる機能を追加しました。

2023-03-24 06:33 UTC, Autumn60 commented
画素座標と経過時間をシード値としたランダムノイズを追加

2023-06-30 06:32 UTC, merged